name: Call a reusable workflow and use its outputs

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    uses: yamini9091/github-actions/.github/workflows/template.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output
        run: |
          # Read the random output from the job-level output
          random_string=${{ needs.set_output_job.outputs.random-output }}
          echo "The random output is $random_string"
