name: Call a Reusable Workflow and Use Its Outputs

on:
  push:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Call Set Output Job
        uses: yamini9091/github-actions/.github/workflows/template.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output
        run: |
          # Read the random output from the job1-level output
          random_string=${{ needs.job1.outputs.random-output }}
          echo "The random output is $random_string"
